source "https://rubygems.org"
# ruby RUBY_VERSION
gem "jekyll", "3.3.1"

gem "theme-NAME", path: "theme-NAME"
gem "mini_magick"
gem "autoprefixer-rails"
gem "sprockets-es6"

group :jekyll_plugins do
  # gem "jekyll-github-metadata", "~> 1.0"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-assets"
  gem "jemoji"
end
